<a href="https://colab.research.google.com/github/Inna-Grynishak/Inna-Grynishak/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота №2
студентки КН-31 **Гринішак Інни**\
**Тема**: TensorFlow\
\
**Завдання:** \
1. За матеріалами ознайомитись із засадами бібліотеки TensorFlow:
- засвоєння поняття тензору
- знати різні способи створення тензорів
- створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)
- продемонструвати основні математичні операції над тензорами
- провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)
2. Відповіді оформити .ipynb документами за кожним з попередніх пунктів
3. Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab2 де мають бути .ipynb файл та необхідні файли з даними



# Завдання 2
Знати різні способи створення тензорів

In [4]:
import  tensorflow  as  tf 
import numpy as np

#vector
vector = tf.constant([10, 10])
print(vector)

#matrix
matrix = tf.constant([[10, 7], [7, 10]])
print(matrix)

#changeble
changeable_tensor = tf.Variable([10, 7])
print(changeable_tensor)

#random
randomN = tf.random.Generator.from_seed(22)
randomN = randomN.normal(shape=(3, 2))
print(randomN)

# ones
tf.ones(shape=(3, 2))


tf.Tensor([10 10], shape=(2,), dtype=int32)
tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor(
[[-0.7531523   2.0261486 ]
 [-0.06997604  0.85445154]
 [ 0.1175475   0.03493892]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

# Завдання 3
Створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)

In [7]:
#matrix
matrix = tf.constant([[10, 3], [5, 8]])
print(matrix, '\n')

print('Shape: ',matrix.shape, '\n')
print('Rank: ',matrix.ndim, '\n')
print('Size: ', tf.size(matrix).numpy(), '\n')
print('Last axis : ',matrix.shape[-1], '\n')

tf.Tensor(
[[10  3]
 [ 5  8]], shape=(2, 2), dtype=int32) 

Shape:  (2, 2) 

Rank:  2 

Size:  4 

Last axis :  2 



# Завдання 4
Продемонструвати основні математичні операції над тензорами

In [8]:
print(matrix)
print('\n Addition: \n', matrix + 10)
print('\n Multiplication: \n', tf.multiply(matrix, 10))
print('\n Subtraction: \n', matrix - 10)
print('\n Matrix mutliplication: \n', matrix @ matrix)
print('\n Matrix mutliplication_var2: \n', tf.matmul(matrix, matrix))

print('Min: ',tf.reduce_min(matrix))
print('Max: ',tf.reduce_max(matrix))
print('Sum: ',tf.reduce_sum(matrix))

tf.Tensor(
[[10  3]
 [ 5  8]], shape=(2, 2), dtype=int32)

 Addition: 
 tf.Tensor(
[[20 13]
 [15 18]], shape=(2, 2), dtype=int32)

 Multiplication: 
 tf.Tensor(
[[100  30]
 [ 50  80]], shape=(2, 2), dtype=int32)

 Subtraction: 
 tf.Tensor(
[[ 0 -7]
 [-5 -2]], shape=(2, 2), dtype=int32)

 Matrix mutliplication: 
 tf.Tensor(
[[115  54]
 [ 90  79]], shape=(2, 2), dtype=int32)

 Matrix mutliplication_var2: 
 tf.Tensor(
[[115  54]
 [ 90  79]], shape=(2, 2), dtype=int32)
Min:  tf.Tensor(3, shape=(), dtype=int32)
Max:  tf.Tensor(10, shape=(), dtype=int32)
Sum:  tf.Tensor(26, shape=(), dtype=int32)


# Завдання 5
Провести CRUD операції над даними, reshape, інтеграцію з np.array)

In [15]:
matrix = tf.constant([[10, 3], [5, 8], [2, 1], [0, 4], [-4, 1]])
# reshape
print(tf.reshape(matrix, [2,5]))

#інтеграція з np.array
print(np.array(matrix))
print(type(np.array(matrix)))

tf.Tensor(
[[10  3  5  8  2]
 [ 1  0  4 -4  1]], shape=(2, 5), dtype=int32)
[[10  3]
 [ 5  8]
 [ 2  1]
 [ 0  4]
 [-4  1]]
<class 'numpy.ndarray'>
